### ISSUE TITLE
Conditional operator always yields 'false'

### ISSUE THREAD

**Issue by JohnWu-Pro** [thymol/thymol.js#10]
Found in version: 2.0.0-beta2

If-then-else: (if) ? (then) : (else) always yields 'false', not the 'then' part, nor the 'else' part.

For example: 
```
${1==1 ? 'TRUE_VALUE':'FALSE_VALUE'} ==> 'false'
```

However, the following expression yields right result:
```
${#bools.isTrue(1==1) ? 'TRUE_VALUE':'FALSE_VALUE'} ==> 'TRUE_VALUE'
```

**Comment by jjbenson** [comment]
Hi,

  Many thanks for taking the time to report this. You have found a serious regression defect.

  The issue was caused by inappropriate binding of the equality operator.

  You should find that the following would work as expected:
<pre>${(1==1) ? 'TRUE_VALUE':'FALSE_VALUE'} ==> 'false'</pre>

  I have coded a fix for the cases that you identified and pushed this to the head. You can grab a snapshot copy with the fix here: https://github.com/thymol/thymol.js/tree/2.x-master.

Thanks again!

  Jim

**Comment by jjbenson** [comment]
Hi JohnWu-Pro,

In the absence of any further comment I am assuming that this issue can now be closed. Please re-open if you find any problems.

Kind Regards,

    Jim
