### ISSUE TITLE
Double ampersand (&&) breaks expression evaluation

### ISSUE THREAD

**Issue by mikonsaari-yepzon** [thymol/thymol.js#26]
Hi,

Any double ampersands in `th:with` breaks expression evaluation and raises error `unknown character`.

Tested with: 2.0.1-pre.7

To reproduce open
```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript">var thVars = [["siteName", "Test site"]]</script>
    <script type="text/javascript" src="./thymol.js"></script>
</head>
<body>
	<span th:with="spanText=${siteName != null && siteName != '' ? siteName : ''}" th:text="${spanText}">
	</span>
</body>
</html>
```
Expected result: <span> tag would contain text Test site
Actual result: <span> tag is empty

**Comment by jjbenson** [comment]
Hi,

There are a few things going wrong here.

1.  Top level scripts are executed in order as the initial html is parsed so moving the thVars declaration after the Thymol load is better.
   You should make sure thVars is declared and in scope before it's used, so put it's declaration in a thymol.ready call. This will be invoked before template processing.

2. The "with" attribute in the span is missing the prefix and won't be recognised by Thymol.

3. I might be wrong about this, but the expression in the "with" body should be in Thymeleaf standard dialect expression language, I don't know if "&&" means "logical and" in that syntax, Thymol doesn't recognise it as such, replacing this with "and" will work. This may be a bug.

```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="./thymol.js"></script>
    <script type="text/javascript">thymol.ready( function(){ thVars = [["siteName", "Test site"]] } );</script>
</head>
<body>
	<span th:with="spanText=${siteName != null and siteName != '' ? siteName : ''}" th:text="${spanText}">
	</span>
</body>
</html>
```
Kind Regards,

  Jim

**Comment by mikonsaari-yepzon** [comment]
Hi,

About the `thVars`, thank you for the suggestion, I initially used the `data-thymol-load` to point to a dummy-data file, but when creating a new template I could not just copy paste the thymol-script-tag since the path for the datafile is relative needed to be corrected.

Keeping the `thVars` with the actual file is much more cleaner and provides some customization for each template, and I haven't had any issues yet with `thVars` being declared like in my example.

I didn't quite understand your second point, do you mean the `spanText` assigment?
It's mentioned in the [Thymeleaf documentation](https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#local-variables ).

As for your third point, I did some digging and you're right, `and` is the supported Thymeleaf expression and `&&` is a Spring Expression Language addition. I've only just started using Thymeleaf and these differences are quite confusing. I can close this issue if you are not SPEL additions in Thymol.

**Comment by jjbenson** [comment]
Hi,

  The latest version deletes any pre-existing definition of thVars when intialising - it does this so that the code can be re-entrant (mainly for the node.js version). As a result, setting of thVars before loading thymol.js is complete won't have the desired effect.

  Putting thVars initialisation in a thymol.ready call keeps the declaration in the actual file - see my re-work of your example above.

  On the 2nd point: in your example above the "with" attribute is missing the thymeleaf namespace prefix, it should say "th:with". Without the prefix the attribute is ignored - this is the basis of thymeleaf.

  Finally - I hear you about standard versus spring compatible dialect! I don't intend to write a SPEL variant of thymol.ThParser. If someone wants to give it a go, they can find the current version in src/main/js/core/thymol-parser.js and good luck to them!

Kind Regards,

  Jim

**Comment by mikonsaari-yepzon** [comment]
I understand your 2nd point, that was a mistake in me setting up the example document, and earlier I was staring at your fixed version with the `th:` added. I fixed the example, since the issue appears only when the attribute is in the correct format.

I will close this is issue, thanks for helping out figuring the root cause being SPEL support not supported by Thymol.

So the solution is to replace any `&&` expression with `and`.
